version: '3.8'

services:

  mariadb:
    command: ["./mariadb.sh"]
    container_name: mariadb
    networks:
      - inception #Network it belongs to
    build:
      context: ./requirements/mariadb #Dockerfile location
    env_file: .env #Environnement pour transmettre les variables
    volumes:
      - mariadb:/var/lib/mysql #Stocker localement les dossiers de /var/lib/mysql dans le volume mariadb
    restart: unless-stopped #Redemarre quand on stop
    healthcheck:
      test: mysqladmin ping --host=localhost -p${MYSQL_ROOT_PASSWORD}
      interval: 5s
      timeout: 1s
      retries: 20
      start_period: 5s
    expose:
      - "3306" #Port à exposer
  
  nginx:
    container_name: nginx
    volumes:
      - wordpress:/var/www/html #Stocker localement les dossiers de /var/www/wordpress dans wordpress
    networks:
      - inception
    depends_on:
      - wordpress #Ne pas démarrer NGINX tant que WordPress n'a pas démarré.
    build:
      context: requirements/nginx
    env_file: .env
    ports:
      - "443:443" #Indique le port qui sera exposé a la machine locale
    healthcheck:
      test: 'curl -kfsSL https://localhost:443' #Checks if the Nginx server is reachable via HTTPS on localhost:443
      interval: 5s
      timeout: 1s
      retries: 10
      start_period: 5s
    restart: on-failure #Redemarrer en cas de crash
  
  wordpress:
    command: ["./auto_config.sh"]
    container_name: wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    build:
      context: ./requirements/wordpress
    depends_on:
      mariadb: #Ne pas démarrer WordPress tant que MariaDB n'a pas démarré (sinon il ne pourra pas configurer la base de données...)
        condition: service_healthy
    restart: on-failure
    expose:
      - "9000"

volumes:
  wordpress:
    driver: local #Stockage de volume en local
    driver_opts:
      type: none
      o: bind
      device: /home/pbureera/data/html #L'endroit pour stocker localement sur l'ordinateur
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/pbureera/data/mysql

networks:
  inception:
    name: inception
    driver: bridge #Installe automatiquement les règles qui permettront aux 3 containers de communiquer en bridge